### ISSUE TITLE
Remove Multiple Lists in Redo App

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-sdk-flutter#17]

**Comment by aboodman** [comment]
Can we close this now? There's no reason to do this right now.

**Comment by arv** [comment]
I think we should probably remove the concept of changing lists too to make things simpler.

**Comment by aboodman** [comment]
+1

**Comment by aboodman** [comment]
Can you just do this in the UI? I think it's important to demonstrate that the data model can be complex , have permissions, etc on the backend.
